---
- hosts: ub1804-webservers
  remote_user: johnoraw
  tasks:
   - name: Install apache2
     apt: name=apache2 update_cache=yes state=latest
   - name: Start the service
     service: name=apache2 state=started
   - name: Open firewall port 80
     ufw: rule=allow port=80 proto=tcp
   - name: Open firewall port 443
     ufw: rule=allow port=80 proto=tcp
  become: yes
