
---
- hosts: dbservers
  become: true

  tasks:
   - name: Update servers
     apt: update_cache=yes

   - name: Upgrade servers
     apt: upgrade=dist

   - name: Install MariaDB Packages
     apt: name={{item}} state=present update_cache=yes
     with_items:
       - mariadb-client
       - mariadb-common
       - mariadb-server

   - name: Start MariaDB
     service: name=mysql state=started


